MVC_MyHotel_example/Models/Apartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace MVC_MyHotel_example.Models
{
    public class Apartment
    {
        public int ID { get; set; }
        //public int number { get; set; }
        public int floor { get; set; }
        public int rooms { get; set; }
        public string description { get; set; }
        [DisplayName("price")]
        public int rating { get; set; }
        public string image { get; set; }
        public int hotelID { get; set; }
        public bool booked { get; set; }
    }
}

MVC_MyHotel_example/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC_MyHotel_example.Models
{
    public class Hotel
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public int stars { get; set; }
        public string image { get; set; }
    }
}

MVC_MyHotel_example/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_MyHotel_example.Models;
using System.IO;

namespace MVC_MyHotel_example.Controllers
{
    public class HotelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Hotels
        public ActionResult Index()
        {
            return View(db.Hotels.ToList());
        }

        public ActionResult Apartments(int? id)
        {
            ViewData["hotelID"] = id;
            ViewData["Hotel"] = db.Hotels.Where(h => h.ID == id).FirstOrDefault();
            return View(db.Apartments.Where(a => a.hotelID == id).ToList());
        }

        // GET: Hotels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // GET: Hotels/Create
        public ActionResult Create()
        {
            if (User.IsInRole("Administrator"))
            {
                return View();
            }
            else
                return RedirectToAction("NoAccess", "Home");
        }

        // POST: Hotels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,name,address,city,stars")] Hotel hotel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Hotels.Add(hotel);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(hotel);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,name,address,city,image,stars")] Hotel hotel, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                var fileName = Path.GetFileName(file.FileName);
                var ext = Path.GetExtension(file.FileName);

                string name = Path.GetFileNameWithoutExtension(fileName);
                string myfile = name + "_" + hotel.ID + ext;
                var path = Path.Combine(Server.MapPath("~/Content/HotelsImg"), myfile);

                hotel.image = myfile;
                db.Hotels.Add(hotel);
                db.SaveChanges();

                file.SaveAs(path);

                return RedirectToAction("Index");
            }
            return View(hotel);
        }

        // GET: Hotels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (User.IsInRole("Administrator"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Hotel hotel = db.Hotels.Find(id);
                if (hotel == null)
                {
                    return HttpNotFound();
                }
                return View(hotel);
            }
            else
                return RedirectToAction("NoAccess", "Home");
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,name,address,city,stars,image")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotel);
        }

        // GET: Hotels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (User.IsInRole("Administrator"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Hotel hotel = db.Hotels.Find(id);
                if (hotel == null)
                {
                    return HttpNotFound();
                }
                return View(hotel);
            }
            else
                return RedirectToAction("NoAccess", "Home");
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hotel hotel = db.Hotels.Find(id);
            db.Hotels.Remove(hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_MyHotel_example/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_MyHotel_example.Models;

namespace MVC_MyHotel_example.Controllers
{
    //[Authorize(Roles = "Administrator")]
    public class ReservationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reservations
        public ActionResult Index()
        {
            if (User.IsInRole("Administrator"))
            {
                var reservations = db.Reservations.Include(r => r.Apartment);
                return View(reservations.ToList());
            }
            else
                return RedirectToAction("NoAccess", "Home");
        }

        public ActionResult MyReservations()
        {
            if (Request.IsAuthenticated && !User.IsInRole("Administrator"))
            {
                string CustomerUsername = User.Identity.Name;
                var reservations = db.Reservations.Include(r => r.Apartment);
                return View(reservations.Where(r => r.CustomerUsername == CustomerUsername).ToList());
            }
            else
                return RedirectToAction("NoAccess", "Home");
        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservations/Create
        //public ActionResult Create()
        //{
        //    ViewBag.ApartmentId = new SelectList(db.Apartments, "ID", "description");
        //    return View();
        //}

        public ActionResult Create(int ApartmentId, string CustomerUsername)
        {
            if (Request.IsAuthenticated && !User.IsInRole("Administrator"))
            {
                ViewData["ApartmentId"] = ApartmentId;
                ViewData["CustomerUsername"] = CustomerUsername;
                ViewBag.ApartmentId = new SelectList(db.Apartments, "ID", "description");
                return View();
            }
            else
                return RedirectToAction("NoAccess", "Home");
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CustomerUsername,CustomerName,CustomerSurname,From,To,ApartmentId")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Apartments.Where(a => a.ID == reservation.ApartmentId).FirstOrDefault().booked = true;
                db.Reservations.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("MyReservations");
            }

            ViewBag.ApartmentId = new SelectList(db.Apartments, "ID", "description", reservation.ApartmentId);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Request.IsAuthenticated && !User.IsInRole("Administrator"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Reservation reservation = db.Reservations.Find(id);
                if (reservation == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ApartmentId = new SelectList(db.Apartments, "ID", "description", reservation.ApartmentId);
                return View(reservation);
            }
            else
                return RedirectToAction("NoAccess", "Home");
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CustomerUsername,CustomerName,CustomerSurname,From,To,ApartmentId")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyReservations");
            }
            ViewBag.ApartmentId = new SelectList(db.Apartments, "ID", "description", reservation.ApartmentId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Request.IsAuthenticated && !User.IsInRole("Administrator"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Reservation reservation = db.Reservations.Find(id);
                if (reservation == null)
                {
                    return HttpNotFound();
                }
                db.Apartments.Where(a => a.ID == reservation.ApartmentId).FirstOrDefault().booked = false;
                return View(reservation);
            }
            else
                return RedirectToAction("NoAccess", "Home");
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("MyReservations");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_MyHotel_example/Views/Hotels/Apartments.cshtml
@model IEnumerable<MVC_MyHotel_example.Models.Apartment>
@using MVC_MyHotel_example.Models;

@{
    ViewBag.Title = "Apartments";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string hotelID = ViewData["hotelID"].ToString();
    string CustomerUsername = HttpContext.Current.User.Identity.Name;
    Hotel hotel = (Hotel)ViewData["hotel"];
}

<header class="cover">
    <div class="overlay">
        <div class="container">
            <div class="row">
                
                <div class="cover-hotel-info">
                    <div class="no-stars text-right pull-right">
                        <p>Number of Stars:</p>
                        @for(int i=0; i<@hotel.stars; i++){
                            <i class="fa fa-star" aria-hidden="true"></i>
                        }

                    </div>
                    
                    <div class="left-info">
                        <h2>@hotel.name</h2>
                        <p><span class="address">@hotel.address</span> in <span class="city">@hotel.city</span></p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if(User.IsInRole("Administrator")){
                <p>
                @Html.ActionLink(
                "Add apartment",                                                  // linkText
                "Create",                                    // actionName
                "Apartments",                                                   // controllerName
                new
                {                                                     // routeValues
                    hotelID = hotelID
                },
                new {@class = "add-apartment"}                                                     //htmlAttributes
            )
            </p>
            }

        </div>
    </div>
</div>



<section id="hotel-apartments">
    <div class="container">

        <div class="row">
            
            <div class="big-title text-center">
                <h1>APARTMETNTS IN THIS HOTEL</h1>
                <div class="line"></div>
            </div>
           
        </div>

        

        <div class="row">

            @foreach (var item in Model) {
    
                <div class="col-md-6">
                <div class="apartment-box">

                    @if(User.IsInRole("Administrator"))
                    {
                    <div class="opton-btns">
                            
                            <a href="@Url.Action("Edit", "Apartments", new { id=item.ID })" class="edit">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>

                            <a href="@Url.Action("Delete", "Apartments", new { id=item.ID })" class="delete">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>


                        </div>
                    }

                    <p class="price-cont">
                        $ <span class="price">@Html.DisplayFor(modelItem => item.rating)</span>/night
                    </p>
                
                    <div class="img-cont">
                        <img src="/Content/ApartmentsImg/@item.image" class="img-responsive" alt="">
                    </div>

                    <div class="box-body">

                        <div class="pull-right">
                            <p class="rooms">Rooms: <span class="">@Html.DisplayFor(modelItem => item.rooms)</span>
                            </p>
                        </div>
                        
                        <div class="">
                            <p class="floor">Floor: <span class="">@Html.DisplayFor(modelItem => item.floor)</span>
                            </p>
                        </div>
                        
                        <div class="clearfix"></div>
                        
                        <div class="">
                            <p class="description">Description:</p>
                            <p>@Html.DisplayFor(modelItem => item.description)</p>
                        </div>
                    </div>

                    

                    @if(!item.booked){
                        <div class="bottom-link book">
                            @Html.ActionLink("BOOK NOW", "Create", "Reservations", new { ApartmentId = item.ID, CustomerUsername = CustomerUsername }, null)
                        </div>
                    }
                    else{
                        <div class="bottom-link not-book">
                            <a href="#">AREADY BOOKED</a>
                        </div>
                    }

                </div>
            </div>


            }
            

        </div>
    </div>
</section>

MVC_MyHotel_example/Views/Hotels/Create.cshtml
@model MVC_MyHotel_example.Models.Hotel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script type="text/javascript">

   function show(input) {
      if (input.files && input.files[0]) {
      var filerdr = new FileReader();
      filerdr.onload = function (e) {
         $('#user_img').attr('src', e.target.result);
      }
      filerdr.readAsDataURL(input.files[0]);
   }
}
</script>

@using (Html.BeginForm("Create", "Hotels", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
/*@using (Html.BeginForm())*/
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Hotel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            @*<div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>*@
            <div class="col-md-10 col-md-offset-2">
                <img id="user_img" height="200" width="350" style="border:solid" />
            </div>

            <div class="col-md-10 col-md-offset-2">
                <input type="file" title="search image" id="file" name="file" onchange="show(this)" />
            </div>
        </div>
        @*-------------------------------*@

        @*<div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <img id="user_img" height="100" width="150" style="border:solid" />
            </div>

            <div  class="col-md-10 col-md-offset-2">
                <input type="file" title="search image" id="file" name="file" onchange="show(this)" />
            </div>

        </div>*@

        @*-------------------------------*@

        <div class="form-group">
            @Html.LabelFor(model => model.stars, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stars, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stars, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_MyHotel_example/Views/Hotels/Delete.cshtml
@model MVC_MyHotel_example.Models.Hotel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stars)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stars)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC_MyHotel_example/Views/Hotels/Details.cshtml
@model MVC_MyHotel_example.Models.Hotel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stars)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stars)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC_MyHotel_example/Views/Hotels/Edit.cshtml
@model MVC_MyHotel_example.Models.Hotel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hotel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden="true">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stars, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stars, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stars, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_MyHotel_example/Views/Hotels/Index.cshtml
@model IEnumerable<MVC_MyHotel_example.Models.Hotel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<header class="cover">
    <div class="overlay">
        <div class="container">
            <div class="row">
                
                <div class="big-title text-center">
                    <h1>BROWSE HOTELS</h1>
                    <div class="line"></div>

                    @if(User.IsInRole("Administrator"))
                    {
                        <a href="@Url.Action("Create")" class="create-new">
                            <i class="fa fa-plus" aria-hidden="true"></i> ADD NEW HOTEL
                        </a>
                    }
                </div>

            </div>
        </div>
    </div>
</header>


<div id="all-hotels">
    <div class="container">
        

        <div class="row">
            
            @foreach (var item in Model) {

                <div class="col-md-3">
                    <div class="hotel-box">

                        @if(User.IsInRole("Administrator"))
                        {
                        <div class="opton-btns">
                            
                            <a href="@Url.Action("Edit", new { id=item.ID })" class="edit">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>

                            <a href="@Url.Action("Delete", new { id=item.ID })" class="delete">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </a>


                        </div>
                        }
                        <p class="price-cont">
                            $ <span class="price">35</span>/night
                        </p>
                    
                        <div class="img-cont">
                            <img src="~/Content/HotelsImg/@item.image" class="img-responsive" alt="">
                        </div>

                        <div class="box-body">
                            <h4 class="name">@Html.DisplayFor(modelItem => item.name)</h4>
                            <div class="address-line">
                                <p class=""><span class="address">@Html.DisplayFor(modelItem => item.address)</span> in <span class="city">@Html.DisplayFor(modelItem => item.city)</span>
                                </p>
                            </div>

                            <div class="">
                                <p class="pull-left">Stars:</p>
                                <div class="no-stars pull-right" number="@Html.DisplayFor(modelItem => item.stars)">
                                    

                                    @for(int i=1; i<=item.stars; i++){
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    }

                                    
                                </div>
                            </div>
                        </div>

                        <div class="bottom-link">
                            @Html.ActionLink("VIEW APARTMENTS", "Apartments", new { id = item.ID })
                        </div>

                    </div>
                </div>

            }

        </div>
    </div>
</div>